# Generated by Django 5.0.7 on 2024-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AddField(
            model_name='profile',
            name='fonction',
            field=models.CharField(default='personnel', max_length=150, verbose_name='Fonction'),
        ),
    ]
