services:
  - type: web
    name: aguipex-rapport
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn projet.wsgi:application"
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "projet.settings"
      - key: SECRET_KEY
        value: django-insecure-2p#-36yb681&=o_(6-bes&naqp_a$9+t#^raaqq9%7i*pz+b2z
      - key: DATABASE_URL
        value: postgresql://aguipex_rapport_user:VoYrysotFB2EN9FGn6u0vmg83bYCu4JO@dpg-cqoochij1k6c73d5o7sg-a.oregon-postgres.render.com/aguipex_rapport
