# Generated by Django 5.0.7 on 2024-07-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='meetingreview',
            name='user',
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='full_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nom complet'),
            preserve_default=False,
        ),
    ]
