# Generated by Django 5.0.7 on 2024-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_remove_meetingreview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_status',
            field=models.CharField(choices=[('programmer', 'Programmer'), ('en_cours', 'En cours'), ('terminer', 'Terminer')], default='programmer', max_length=15, verbose_name='Statut de la réunion'),
        ),
    ]
